# contractshark workflow pipeline
#  spdx-license-identifier: ISC
#  v0.2.4
name: contractshark

on: ["pull_request"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node: ["12.x"]
        os: ["ubuntu-latest"]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
      - name: yarn install and build
        run: |
          yarn install
<<<<<<< HEAD

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
=======
          yarn compile
      - name: yarn test and coverage
        run: |
          yarn test 
          yarn coverage
>>>>>>> 57993ef1ec6f9346f22ad42b0960b8ab147a88fd
