name: nodejs

on: ["push"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node: ["12.x"]
        os: ["ubuntu-latest"]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
      - name: install and build
        run: |
          npm install
          npx hardhat compile

      - name: test and coverage
        run: |
          npm run-script hardhat:test
          npm run-script coverage
